### ISSUE TITLE
manipulating data lab

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/DaSEH#100]
1.3 could probably be simplified

**Comment by carriewright11** [comment]
yeah people got confused if they had tried one column and then it no longer worked to rename it again when they had more of the code. Maybe we just give them the code? or we could at least add troubleshooting tips though, also for 1.4 ... could add more to the hint about `starts_with()` and 1.6 quotes

**Comment by avahoffman** [comment]
also inconsistencies in the quotation marks for pivoting column names... what the heck

**Comment by avahoffman** [comment]
underscore in summary

**Comment by carriewright11** [comment]
> underscore in summary missing for `antijoin`

I have that in another issue for the lecture

**Comment by carriewright11** [comment]
> also inconsistencies in the quotation marks for pivoting column names... what the heck

yeah - we could point people to the guide/walk people through the guide

**Comment by carriewright11** [comment]
part 2 hint for 2.4 "index" confused some people maybe say column or variable instead... could also suggest the count function which would be a bit simpler

**Comment by avahoffman** [comment]
> > also inconsistencies in the quotation marks for pivoting column names... what the heck
> 
> yeah - we could point people to the guide/walk people through the guide

The issue is that I SWEAR it didn't used to work without quotes and now it does. So inconsistent.
