### ISSUE TITLE
data visualization lecture

### ISSUE THREAD

**Issue by ehumph** [fhdsl/DaSEH#106]
For slide #24, the `set.seed(123)` is not necessary since you're filtering the data, not doing a slice sample

**Comment by carriewright11** [comment]
thank you!

**Comment by ehumph** [comment]
Slide #62 <- remove the quotes around plotly in the command `library("plotly")`

**Comment by carriewright11** [comment]
maybe we need a slide saying this section is more for experienced folks or to grow into? especially post lab 1
