### ISSUE TITLE
factors

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#108]
- [x]  this slide https://daseh.org/modules/Factors/Factors.html#19 about forcats for ordering , the size of the font is very small... and for the subsequent slides

**Comment by carriewright11** [comment]
This slide doesn't fit: forcats for ordering.. can be used to sort datasets
or the slide on change to a factor: https://daseh.org/modules/Factors/Factors.html#12

**Comment by ehumph** [comment]
Slide #15 still says "arrange data by grade" in the title. Should instead be "arrange data by age"

**Comment by ehumph** [comment]
Slide #23 the comments explaining how the factor is being reordered need to be updated

**Comment by carriewright11** [comment]
slide 19 forcats for ordering extra ` after `RATE`

**Comment by carriewright11** [comment]
file:///Users/carriewright/Documents/GitHub/DaSEH/modules/Factors/Factors.html#9 slide 9 - the data - it should say it will assume alphanumerical

**Comment by carriewright11** [comment]
> Slide #23 the comments explaining how the factor is being reordered need to be updated
This appears to be resolved

**Comment by carriewright11** [comment]
> slide 19 forcats for ordering extra `after`RATE`

This appears to be resolved

**Comment by carriewright11** [comment]
the remaining issues are resolved in PR #218
