### ISSUE TITLE
functions update

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#121]
people seem confused about when to use R
- maybe add another slide showing this some more?

**Comment by carriewright11** [comment]
the lab p2 - could add more info - maybe just the code, cause people don't often realize that x>10 will give a logical vector as output

**Comment by carriewright11** [comment]
Last question  of lab - x and y are switched and it asks for code from 2.4 which isn't a question that is labeled

**Comment by cansavvy** [comment]
I'm going to attempt to address these bugs but I may have more questions when I look at it.

**Comment by cansavvy** [comment]
> the lab p2 - could add more info - maybe just the code, cause people don't often realize that x>10 will give a logical vector as output

Which lab is P2? https://daseh.org/materials_schedule.html I'm not seeing these designations where I am looking.

**Comment by cansavvy** [comment]
I've found it but I'm not 100% sure the changes I made address what you are thinking @carriewright11 so I will ask for review.
