### ISSUE TITLE
homework 2 greater than or equal to

### ISSUE THREAD

**Issue by franznat** [fhdsl/DaSEH#122]
Either the question should be rephrased or the code should be changed - it asks about days _above_ 0 degrees but the answer includes temps _at_ 0 degrees. There are 218 days _at or above_ but only 159 _above_.

> 13. How many data points are from days where the maximum ground temperature got above 0 degrees Celsius? What percent/proportion do these represent? Use:
> filter() and nrow()
> group_by() and summarize() or
> sum()
> # How many data points are from days where the maximum ground temperature got above 0 degrees Celsius?
> nrow(mars %>% filter(max_ground_temp >= 0))
> ## [1] 218

**Comment by carriewright11** [comment]
thank you!!

**Comment by carriewright11** [comment]
This is done
