### ISSUE TITLE
Update instructors and TAs information

### ISSUE THREAD

**Issue by cansavvy** [fhdsl/DaSEH#15]
## Summary 

The `modules/Intro/Intro.Rmd` files has information about the instructors and TAs! But its leftover from the intro_to_r course. 

In #14,  

- I removed Cliff (sorry Cliff) Because I don't think he will be teaching this information. 
- I added Elizabeth because I think she will be. But I didn't know what info she wanted. 
- I didn't know if I will be teaching or not so I did not add myself. 
- I also didn't know if we know who are TAs are (or if they exist)

**Comment by avahoffman** [comment]
Thank you! I edited the front page via the `config.yml` file to update this as well. What you added in #14 is good to tide us over.
