### ISSUE TITLE
Remove references to dasehr package (for Oct 2024 session)

### ISSUE THREAD

**Issue by ehumph** [fhdsl/DaSEH#151]
To make things easier, we're not using the dasehr package

**Comment by avahoffman** [comment]
I would still like to use the dasehr package but I think we can simplify the usage.

**Comment by carriewright11** [comment]
I am not quite sure I know what this means exactly - I tried looking at the summarization lecture, but I am still not sure.

**Comment by avahoffman** [comment]
@carriewright11 bring data into R using the URL, not `dasehr`. I think it's just a little too confusing for folks to set up.
