### ISSUE TITLE
What should be described to DaSEH students about course evaluations?

### ISSUE THREAD

**Issue by cansavvy** [fhdsl/DaSEH#16]
## Summary 

In syllabus.Rmd there was a description of how students will evaluate the intro_to_r course at JHU. In #14 this was removed. 

What should be told to the students about how they can evaluate the DaSEH course? What plans are already in place and do we need to make a survey or something?

**Comment by avahoffman** [comment]
We will definitely survey the students, and we also have IRB approval to do so. We'll add these soon!

**Comment by carriewright11** [comment]
I can change it to be vague for now! (and not about jhu)
