### ISSUE TITLE
Is `sample_n` described earlier? Use instead of `slice_sample`

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/DaSEH#161]
- [ ] Is `sample_n` described earlier? Use instead of `slice_sample`

_Originally posted by @avahoffman in https://github.com/fhdsl/DaSEH/pull/148#discussion_r1768824668_

**Comment by carriewright11** [comment]
`slice_sample()` is in the subsetting lecture. `sample_n()` has been superseded in favor of `slice_sample()`

**Comment by carriewright11** [comment]
The subsetting lecture is before the data classes lecture, where you wrote this comment, so it will have already been introduced.
