### ISSUE TITLE
update the script for making labs from lab keys

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#178]
in PR #176 I updated the R script for making labs from the lab keys to ignore the RStudio lab, because the use case doesn't align as well.
- currently want people to change things in a chunk, so it would be nice if the key showed the change
- want people to learn how to add chunks, the blank empty chunks make that kinda odd
- people got confused by the empty chunks last time because they aren't as response -like as the other labs

maybe we can update the script to instead of ignore the RStudio lab, it only copies the text and ignores the chunks or something?

**Comment by carriewright11** [comment]
hmmm actually that would also mess up the extra header that I add in the key - but maybe we could have it ignore that

**Comment by avahoffman** [comment]
if you just put {r} instead of {r 1.1response} it will ignore the chunk!

**Comment by carriewright11** [comment]
hmmm it will still make the new header...

**Comment by carriewright11** [comment]
Just tried this.. and the answer of creating a new chunk shows like the chunks that have code in them like the initial installing packages, which is what I thought would happen but not actually what I want... also shows the answer for the new header. I think it might be best to revert all those changes and going back to not rendering the lab from the key? Maybe we can come up with a better solution though later.
