### ISSUE TITLE
Link to posit cheatsheets at the end of lectures (where we link to our own as well)!

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#179]
I think it would be great to link to posit cheatsheets at the end of lectures (where we link to our own as well)!

_Originally posted by @avahoffman in https://github.com/fhdsl/DaSEH/issues/99#issuecomment-2377453139_

**Comment by avahoffman** [comment]
- [ ] Basic R (not applicable?)
- [ ] RStudio
- [ ] Reproducibility
- [X] Data Input
- [ ] Subsetting Data in R
- [ ] Data Summarization
- [ ] Data Classes
- [ ] Data Cleaning
- [ ] Manipulating Data in R
- [ ] Intro to Data Visualization
- [ ] Data Visualization
- [ ] Factors
- [ ] Statistics
- [ ] Data Output
- [ ] Functions

**Comment by avahoffman** [comment]
Make sure they're also all the same emoji (lol)

**Comment by carriewright11** [comment]
> Make sure they're also all the same emoji (lol)

did I mess that up?

**Comment by avahoffman** [comment]
> > Make sure they're also all the same emoji (lol)
> 
> did I mess that up?

No that was me
