### ISSUE TITLE
Add gut checks to each lecture

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#184]
simple multiple choice or true or false to engage people

**Comment by avahoffman** [comment]
- [ ] Basic R
- [ ] RStudio
- [ ] Reproducibility
- [ ] Data Input
- [ ] Subsetting Data in R
- [ ] Data Summarization
- [ ] Data Classes
- [ ] Data Cleaning
- [ ] Manipulating Data in R
- [ ] Intro to Data Visualization
- [ ] Data Visualization
- [ ] Factors
- [ ] Statistics
- [ ] Data Output
- [ ] Functions
