### ISSUE TITLE
Basic R lab

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/DaSEH#185]
> Had some awkardness with the rmd file - like people putting their code in all sorts of places... I wonder if for next time we want to just use a script for basic R? or idk there is probably a better way - maybe we could just go over the chunks a tiny bit?

We could just put some questions in an html file/page. Have a key for people but no download required. Just work in the console.

**Comment by carriewright11** [comment]
got this feedback... I think it is from this lab - haven't checked it yet:
FYI this in the lab rmd: ### P.2

Multiply the following `a` and `b` together. How is this similar to the way R performs addition in #10 ?
