### ISSUE TITLE
RStudio Lecture

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/DaSEH#186]
Updating screenshots - noticed the image with this slide:

> Errors
> R studio can help you find issues in your code. Note that sometimes the error occurs earlier than RStudio thinks.

had `print())` which we didn't really talk about. Could be `class()` or `length()`..

**Comment by carriewright11** [comment]
- [ ] cut a bit of info and extra slides from Rstudio 
- [ ] add gut check

**Comment by carriewright11** [comment]
> * [ ]  cut a bit of info and extra slides from RStudio
> * [ ]  add gut check

**Comment by avahoffman** [comment]
Gut check of where does code go??

PICTURE OF CHUNK
