### ISSUE TITLE
Stuff from Rstudio section that could be in Basic R

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#188]
Do we want this stuff - (I am cutting it from RStudio)?

## Lab: Getting started
To do this lab we need to:

- Download the file at the link above by clicking on it or go to the [website](https://daseh.org/materials_schedule.html) schedule page
- Find the downloaded file on your computer
- Open the file in RStudio (double clicking the file name typically works, otherwise right click)
- Might need to restart RStudio

These videos can help if you aren't sure where your downloads are:

If you have a PC: https://youtu.be/we6vwB7DsNU

If you have a Mac: https://www.youtube.com/watch?v=Ao9e0cDzMrE

You can find these on the resource page of the class website.

**Comment by avahoffman** [comment]
I have the download info in Input currently but it can probably be moved to basic R.

**Comment by carriewright11** [comment]
maybe in both places?

**Comment by avahoffman** [comment]
Maybe it should be in the intro? But I'd like to try not to repeat ourselves, since generally less info is better. Also more sustainable :)
