### ISSUE TITLE
subsetting lab

### ISSUE THREAD

**Issue by ehumph** [fhdsl/DaSEH#201]
Lab key is evaluating a version of the ces dataset that has 68 columns, while the actual version has 67.

**Comment by ehumph** [comment]
![image](https://github.com/user-attachments/assets/fa4e3aea-697c-4968-b15f-d342449aa117)

**Comment by carriewright11** [comment]
> Lab key is evaluating a version of the ces dataset that has 68 columns, while the actual version has 67.

This is already resolved just a rendering lag
