### ISSUE TITLE
Subsetting Lecture and Lab

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/DaSEH#203]
Lecture
- [x] The gut check on slide 35 was a bit confusing. Might get rid of the "NOT" and just ask what would work well.
- [x] The gut check on slides 48 was also a bit tricky - some folks got it, but I have been trying to put the gut check immediately after the concept to be "just in time-y"
- [x] Also might consider reframing how `pull()` is discussed.. you mentioned convenience of viewing the values a lot, but I feel like the major reason you really need `pull()` is to make a vector, and I wonder if this confused them
- [x] Slide 65 gut check I would simplify to either testing knowledge of filter() or `|` vs `&` - maybe both is too much? 
- [x] [BUG‼️🐛] Typo at the [beginning of part 3](https://github.com/fhdsl/DaSEH/blob/aeef512564d2ca7047fee06dbcdd7b41efe50c77/modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd#L688) - It should be https://daseh.org/data/CO_ER_heat_visits.csv

Lab
- [x] Remove `library(dplyr)` from the lab, redundant with loading tidyverse. (resolved by #202 )
- [x] Key has the wrong number of columns for `ces`, showing 68 not 67 - probably just needs to rerender.
- [x] Could reorder the 2.5-2.6 questions so that asthma comes first.
- [x] had someone do `filter(ces_sub, Asthma > 100 & Traffic < 500 | Traffic==500)` -- how does order of operations work with filter?

**Comment by carriewright11** [comment]
alignment of the cheetsheets could be fixed for the lab2 slide

**Comment by carriewright11** [comment]
before section 2 would be helfpful to assign reading in the data to er - just like before section 3:
#er <- read_csv("https://daseh.org/data/Colorado_ER_heat_visits.csv")
set.seed(1234)
er_30 <-slice_sample(er, n = 30)

**Comment by carriewright11** [comment]
- [ ] in summary of part 2 point out that there are extra slides on having multiple patterns for selection

**Comment by carriewright11** [comment]
- [ ] add a mention of the new pipe

**Comment by carriewright11** [comment]
>  had someone do filter(ces_sub, Asthma > 100 & Traffic < 500 | Traffic==500) -- how does order of operations work with filter?

I added some extra slides about this
