### ISSUE TITLE
Data viz lab

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/DaSEH#222]
- [x] packages
  ```
  library(readr)
  library(ggplot2)
  library(dplyr)
  ```
  
  could be 
  
  ```
  library(tidyverse)
  ```
- [x] Also, maybe "load the *packages*" instead of "load the *libraries*"
- [x] 1.2 maybe mention that they need the `labs()` function
- [x] I think `color = type` in 2.1 is old, should be CaliforniaCounty
- [x] 2.2 `ncol` arg is not needed - it's already 3 cols

**Comment by carriewright11** [comment]
- [ ] switch out the filter step to use %in% to be consistent with what we taught with filter

**Comment by carriewright11** [comment]
> * [ ]  2.2 `ncol` arg is not needed - it's already 3 cols
Changed to nrow and then asked people to try adjusting
