### ISSUE TITLE
data viz lecture

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/DaSEH#223]
- [x] cheatsheet and lab links at the end of part 1 are missing line breaks 
https://github.com/fhdsl/DaSEH/blob/5c29925732e956c836baf2d508e2a359b4a61094/modules/Data_Visualization/Data_Visualization.Rmd#L490

**Comment by carriewright11** [comment]
- [ ] remove set.seed on slide 24
- [ ] maybe move the gutcheck to before the summary for lab 1
