### ISSUE TITLE
Verify all the lecture images are okay!

### ISSUE THREAD

**Issue by ehumph** [fhdsl/DaSEH#35]
As I've been changing datasets for the lectures and labs, I realized I wasn't checking all the images being called for the lectures. These should be checked and remade if need be to show environmental health datasets!

**Comment by avahoffman** [comment]
- [x] Basic R
- [ ] RStudio
- [ ] Reproducibility
- [ ] Data Input
- [ ] Subsetting Data in R
- [ ] Data Summarization
- [ ] Data Classes
- [ ] Data Cleaning
- [ ] Manipulating Data in R
- [ ] Intro to Data Visualization
- [ ] Data Visualization
- [ ] Factors
- [ ] Statistics
- [ ] Data Output
- [ ] Functions
