### ISSUE TITLE
Grep search for mentions of JHU or jhdsl on website Rmds and replace / remove.

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/DaSEH#7]
Don't worry about links in the content for now.

**Comment by cansavvy** [comment]
I'll try to do this in between meetings today!

**Comment by avahoffman** [comment]
Sweet! Should be mostly straightforward - just stuff in the main Rmds that comprise the website is priority.

**Comment by avahoffman** [comment]
I think this is done!
