### ISSUE TITLE
subsetting data lab fixes

### ISSUE THREAD

**Issue by ehumph** [fhdsl/DaSEH#81]
For one, the dasehr package is loaded twice. 

Line 9 also says "First let's get load our packages" which is clearly nonsense

**Comment by avahoffman** [comment]
Can you duplicate this issue here: https://github.com/jhudsl/intro_to_r if the same typos are there too?

**Comment by avahoffman** [comment]
2.2 uses ER but the columns were previously renamed in 1.3 - might be tricky for folks, don't know if we intended to select both upper and lower limits

**Comment by avahoffman** [comment]
2.7 typo - shoul be 2011

**Comment by avahoffman** [comment]
Numbers are off for part 3

**Comment by avahoffman** [comment]
3.3 Needs to be reworded. 3.1 also has ER_sub which is not referenced before.

**Comment by carriewright11** [comment]
1.3 `population` should say `rate`

**Comment by carriewright11** [comment]
> For one, the dasehr package is loaded twice.
> 
> Line 9 also says "First let's get load our packages" which is clearly nonsense

this seems to be resolved- looking at https://github.com/fhdsl/DaSEH/pull/157/files

**Comment by carriewright11** [comment]
> 2.2 uses ER but the columns were previously renamed in 1.3 - might be tricky for folks, don't know if we intended to select both upper and lower limits

I think this might be ok in the current version - people are told to use the original dataset

**Comment by carriewright11** [comment]
> 3.3 Needs to be reworded. 3.1 also has ER_sub which is not referenced before.

this seems to be ok now

**Comment by carriewright11** [comment]
> 1.3 `population` should say `rate`

this is ok in the current version

**Comment by carriewright11** [comment]
We use er_30 for the subsetting lecture which was also used for the lab, but with a newer PR we now use the CalEnviroScreen dataset for the lab. I Know we were trying to use fewer datasets, but I generally don't mind having people try labs with a different dataset as the one in the lecture, as I think it makes them apply their skills more.

**Comment by carriewright11** [comment]
this is done - mostly with PR https://github.com/fhdsl/DaSEH/pull/157
