### ISSUE TITLE
subsetting lecture fixes

### ISSUE THREAD

**Issue by ehumph** [fhdsl/DaSEH#83]
Slide 83 still has "BUYER_STATE" as the variable being relocated, but the dataset has been changed to CO_heat_ER_bygender

**Comment by carriewright11** [comment]
> Slide 83 still has "BUYER_STATE" as the variable being relocated, but the dataset has been changed to CO_heat_ER_bygender

this appears to be fixed but there were some other issues with this slide that were addressed by PR #165
