### ISSUE TITLE
Summarization explain data

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#89]
There was lots of confusion about the data during the lecture.

Maybe if there were some slides describing that each row has gender specific counts might help

**Comment by avahoffman** [comment]
I think we should just use a different dataset for this one.

**Comment by avahoffman** [comment]
2.3 in the lab was worded wrong

**Comment by avahoffman** [comment]
calenviroscreen score - maybe just look at lead or something I think they didn't understand what the score or percentile was. Or explain the dataset in the lab

**Comment by ehumph** [comment]
Yeah, I don't know what I was thinking when I picked that variable for the lab. It was a bad choice.

**Comment by avahoffman** [comment]
Nah, just might be a slightly easier option :)
