### ISSUE TITLE
data cleaning

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#93]
- [x]   change the percentage calculation to be about emissions: 

yearly_co2 %>% drop_na(`1800`) %>% 
 count(`1800`, country) %>% mutate(percent = (`1800`/(sum(`1800`)) *100))...hmmm or actually that will not quite do what we want... but something like this... tempted to go back to the bike data as it seems kind of environmental

- [x]  subset the data so we can see what is happening better in the earlier slides using slice_sample() - although maybe it was useful to see how I dealt with larger data? the slides could show the simplified data idk

**Comment by carriewright11** [comment]
- [ ] do the na_if replace na in the opposite order so it makes more sense with the data - add explanation as to why we are doing that

**Comment by carriewright11** [comment]
- [ ] find a dataset - make a subset with rare data - maybe just look at the complete data for country or something or get rid of the example about rare data values

**Comment by carriewright11** [comment]
- [ ] can we get away with doing the na replace etc. without the waste water data and just use one dataset?

**Comment by avahoffman** [comment]
Lab link was wrong in the slides - pointed to jhur :(

**Comment by avahoffman** [comment]
petition to get rid of gg_miss_var - I think it's a misrepresentative plot :P

**Comment by avahoffman** [comment]
did we want to remove `data_diet` references?

**Comment by avahoffman** [comment]
Lab: 

- [ ] Probably don't need to load all those packages

**Comment by carriewright11** [comment]
the weight loss should be removed from the lab already if you have the final version

**Comment by carriewright11** [comment]
it should say exposure instead

**Comment by carriewright11** [comment]
hmmm somehow it didn't come through from my last PR

**Comment by carriewright11** [comment]
- [ ] the slide about the toy data didn't fit on the slide

**Comment by carriewright11** [comment]
- [ ] the slide about the toy data didn't fit on the slide

**Comment by carriewright11** [comment]
- [ ] the slide about the toy data didn't fit on the slide

**Comment by carriewright11** [comment]
- [ ] the slide about the toy data didn't fit on the slide

**Comment by ehumph** [comment]
> * [ ]  can we get away with doing the na replace etc. without the waste water data and just use one dataset?

Addressed this in #137. The waste water dataset was replaced with CO ER visits (which also replaced the yearly CO2 dataset)

**Comment by carriewright11** [comment]
> * [ ]    change the percentage calculation to be about emissions:
> 
> yearly_co2 %>% drop_na(`1800`) %>% count(`1800`, country) %>% mutate(percent = (`1800`/(sum(`1800`)) *100))...hmmm or actually that will not quite do what we want... but something like this... tempted to go back to the bike data as it seems kind of environmental
> 
> * [ ]   subset the data so we can see what is happening better in the earlier slides using slice_sample() - although maybe it was useful to see how I dealt with larger data? the slides could show the simplified data idk

This is now er data
