### ISSUE TITLE
adding more posit cheatsheets and more keyboard shortcuts

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/DaSEH#99]
This cheatsheet is very good... I thought we had more on the resource page and maybe we do, but I couldn't find it today: https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_strings.pdf 

Also adding info about %in% shortcut could be good: https://stackoverflow.com/questions/58714081/is-there-a-shortcut-for-in

**Comment by avahoffman** [comment]
I think it would be great to link to posit cheatsheets at the end of lectures (where we link to our own as well)!

**Comment by carriewright11** [comment]
> I think it would be great to link to posit cheatsheets at the end of lectures (where we link to our own as well)!

ah yes, I am going to make a new issue for that
